gpwn/CampFire_BE

src/architecture/controllers/camps.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js, src/config/config.js, src/migrations/20221231053827-create-users.js, src/migrations/20221231053828-create-hosts.js, src/migrations/20221231054630-create-camps.js, src/migrations/20221231054909-create-books.js, src/models/books.js, src/models/camps.js, src/models/hosts.js, src/models/index.js, src/models/users.js, src/routes/camps.route.js, src/routes/index.js
=> <FEAT> DB생성 :card_file_box:

src/migrations/20221231054909-create-books.js, src/models/books.js
db books수정하였습니다.
-db books : peopleAmount -> adults, children
=> <FIX> db books 수정

package-lock.json, package.json, src/app.js, src/architecture/controllers/hosts.controller.js, src/architecture/controllers/users.controller.js, src/architecture/repositories/hosts.repository.js, src/architecture/repositories/users.repository.js, src/architecture/services/hosts.service.js, src/architecture/services/users.service.js, src/middlewares/authHost.middleware.js, src/middlewares/authLogin.middleware.js, src/middlewares/authLoginHost.middleware.js, src/middlewares/authLoginHost.middlewarejs, src/middlewares/authLoginUser.middleware.js, src/middlewares/authUser.middleware.js, src/middlewares/error.handler.middleware.js, src/migrations/20221231053828-create-hosts.js, src/models/hosts.js, src/models/index.js, src/modules/profileImg.js, src/routes/hosts.route.js, src/routes/index.js, src/routes/users.route.js, src/util/auth-encryption.util.js, src/util/auth-jwtToken.util.js
<FEAT> 로그인API기능구현 완료 :sparkles:
=> <FEAT> 로그인API기능구현 완료 :sparkles:

.gitignore, src/architecture/controllers/camps.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js, src/routes/camps.route.js
캠핑장 업로드/페이지 조회/상세 조회 API 구현 완료했습니다.
동일한 파일에서 작업하여 conflict 나는 부분 merge 했습니다.
=> <FEAT> 캠핑장 업로드/페이지 조회/상세 조회 API 기능 구현 :sparkles:

src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js
=> <FIX> camp erorr 추가 :art: Feature/campupdate

.dockerignore, .wslconfig, Dockerfile
=> cicd를 위한 test

src/routes/index.js
=> <FIX> index cicd test 수정

src/routes/index.js
=> <FIX> index cicd test 수정2

src/routes/index.js
=> <FIX> index cicd test 수정3

.github/workflows/main.yml, src/routes/index.js
=> <FIX> commit for cicd test

src/routes/index.js
=> <FIX> cicd test_khj

src/routes/index.js
=> <FIX> cicd test 

src/routes/index.js
=> <FIX> cicd test_khj2

.github/workflows/main.yml
자동배포는 잘 되네 ec2에 퍼블릭 ip로 연결이 되지 않아서 포트를 8080으로 변경했습니다.
=> <FIX> 8080port 변경

.github/workflows/main.yml
cicd test 중 8080테스트 실패하여 80포트로 원상복귀하였습니다.
=> <FIX> 80port로 복귀

.github/workflows/main.yml
cicd test 8080포트를 80포트로 다시 수정하였습니다.
=> <FIX> cicd test

src/routes/index.js
=> <FIX> env git에 설정

.github/workflows/main.yml, src/routes/index.js
=> <FIX> cicd test gir repo env setting

src/app.js
=> <FIX> port 번호 변수로 추가

src/app.js, src/routes/index.js
=> <FIX> port번호 변수로 추가

src/app.js
=> <FIX> port 번호 변수로 추가2

.github/workflows/main.yml
=> <FIX> 환경변수 추가

Dockerfile
=> <FIX> 환경변수 도커 파일에 추가

.github/workflows/main.yml, Dockerfile
=> <FIX> 환경변수 yml추가

.github/workflows/main.yml
=> <FIX> cicd env설정 test

.github/workflows/main.yml
=> <FIX> cicd env설정 test last

.github/workflows/main.yml
<FIX> cicd 환경변수 test envname 추가
=> <FIX> cicd 환경변수 test envname 추가

.github/workflows/main.yml
<FIX> cicd 환경변수 test envname 추가2a
=> <FIX> cicd 환경변수 test envname 추가2a

.github/workflows/main.yml
<FIX> cicd 환경변수 test envname 추가2
=> <FIX> cicd 환경변수 test envname 추가2

.github/workflows/main.yml
<FIX> cicd 환경변수 test envname 추가 env->secrets으로 변경
=> <FIX> cicd 환경변수 test envname 추가 env->secrets으로 변경

.github/workflows/main.yml
=> <FIX> cicd 환경변수 test 오타 수정

.github/workflows/main.yml
=> <FIX> cicd 환경변수 test 오타 수정2

.github/workflows/main.yml
<FIX> cicd 환경변수 test실패 원상태 유지2
=> <FIX> cicd 환경변수 test실패 원상태 유지2

.github/workflows/main.yml
=> <FIX> cicd 환경변수 test 배포시 추가

Dockerfile
<FIX> cicd mysql연결 명령어 dockerfile에 추가
=> <FIX> cicd mysql연결 명령어 dockerfile에 추가

.github/workflows/main.yml, Dockerfile
=> <FIX> cicd mysql연결 DB HOST 추가

.github/workflows/main.yml
=> <FIX> cicd mysql연결 오타수정

.github/workflows/main.yml, src/app.js
=> <FIX> cicd port env test

.github/workflows/main.yml
=> <FIX> cicd port env test2

.github/workflows/main.yml
=> <FIX> cicd port env test3

.github/workflows/main.yml, src/app.js
=> <FIX> cicd 환경변수 test

src/app.js
test를 위해 res.send값을 환경 변수를 제외하고 3000로 변경했습니다.
=> <FIX> cicd test - app.js res.send값 변경

.github/workflows/main.yml
=> <FIX> cicd test 오타 추정 수정 :=>=

.github/workflows/main.yml, src/app.js
환경변수 test를 위해 port번호를 환경변수로 변경하였습니다.
=> <FIX> cicd port 번호 test

src/app.js
=> <FIX> cicd port 번호 test2

.github/workflows/main.yml
<FIX> cicd env cantainer추가 test
=> <FIX> cicd env cantainer추가 test

Dockerfile
DOCKERFILE에 호스트 를 0.0.0.0 -> 1.1.1.1로 변경했습니다.
=> <FIX> dockerfile host 변경

.github/workflows/main.yml
=> <FIX> env추가

src/architecture/repositories/camps.repository.js
camprepository: campAmenity->campAmenities로 수정
=> <FIX> campAmenity->campAmenities로 수정 :recycle:

src/architecture/controllers/camps.controller.js, src/architecture/services/camps.service.js
camp수정시 db에서 중복값을 찾는 에러를 삭제하였습니다
=> <FIX> campupdate error처리 수정 ♻️ 

src/app.js, src/architecture/controllers/camps.controller.js, src/architecture/services/camps.service.js, src/modules/campImg.js, src/modules/modules.js, src/routes/camps.route.js
-camp수정 시 이미지를 삭제 후 이미지 다시 업로드 하도록 수정
-camp삭제 시 s3에 저장된 이미지도 삭제 하도록 수정
=> <FIX> campupdate api bug fix/delete api update :bug:

src/migrations/20221231054630-create-camps.js, src/migrations/20221231054909-create-books.js, src/models/books.js, src/models/camps.js, src/modules/campImg.js
=> <FIX> db정보 수정

src/migrations/20221231054909-create-books.js, src/models/books.js
=> <FIX> 오타수정

src/architecture/controllers/camps.controller.js, src/migrations/20221231054909-create-books.js, src/models/books.js
토탈 피플 값은 추후에 추가하고 우선 db에서 삭제하였습니다.
=> <FIX> 예약하기 버그 수정

src/architecture/controllers/camps.controller.js, src/migrations/20221231053828-create-hosts.js, src/migrations/20221231054631-create-sites.js, src/migrations/20221231054632-create-campAmenities.js, src/migrations/20221231054633-create-envs.js, src/migrations/20221231054634-create-types.js, src/migrations/20221231054635-create-themes.js, src/migrations/20221231054909-create-books.js, src/models/books.js, src/models/campAmenities.js, src/models/camps.js, src/models/envs.js, src/models/sites.js, src/models/themes.js, src/models/types.js
erd에 맞춰 db수정하였습니다. 
현재 배포되어 있는 db에는 추후에 적용 예정입니다.
=> <FIX> db 최신화 :card_file_box:

src/architecture/controllers/books.controller.js, src/architecture/repositories/books.repository.js, src/architecture/services/books.service.js, src/migrations/20221231054630-create-camps.js, src/migrations/20221231054631-create-sites.js, src/models/camps.js, src/models/sites.js, src/routes/books.route.js, src/routes/camps.route.js, src/routes/index.js
<FIX> DB 수정 :card_file_box:
camp에 campPrice 삭제하고
site에 sitePrice 추가 하였습니다.
=> <FIX> DB 수정 :card_file_box:

src/architecture/controllers/books.controller.js, src/architecture/controllers/camps.controller.js, src/architecture/repositories/books.repository.js, src/architecture/repositories/camps.repository.js, src/architecture/services/books.service.js, src/architecture/services/camps.service.js, src/routes/books.route.js, src/routes/camps.route.js, src/routes/index.js
user,host 예약 조회 기능 구현
캠핑장,사이트 목록조회,상세조회 수정
=> <FEAT> user,host 예약 조회 기능 구현 및 캠핑장,사이트 목록조회,상세조회 수정 :art::sparkles:

src/architecture/controllers/camps.controller.js, src/architecture/controllers/sites.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/repositories/sites.repository.js, src/architecture/services/camps.service.js, src/architecture/services/sites.service.js, src/config/config.js, src/routes/camps.route.js, src/routes/index.js, src/routes/sites.route.js
데이터 등록 및 조회시 createdAt과 updatedAt이 한국시간으로 나오지 않아 config 파일에 코드 추가했습니다!
=> <FEAT> 캠핑장 API 수정 및 체크박스 키워드 등록,수정 및 사이트 등록/수정/삭제 API 기능 구현 완료:art::sparkles:

src/routes/camps.route.js
=> <FIX> Dev Post 라우터 연결

src/architecture/controllers/camps.controller.js, src/architecture/controllers/likes.controller.js, src/architecture/repositories/likes.repository.js, src/architecture/services/camps.service.js, src/architecture/services/likes.service.js, src/migrations/20221231053827-create-users.js, src/migrations/20221231054630-create-camps.js, src/migrations/20221231054910-create-likes.js, src/models/camps.js, src/models/likes.js, src/models/users.js, src/routes/index.js, src/routes/likes.route.js
=> <FIX>  캠핑장 등록시 에러

src/architecture/controllers/camps.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js
=> <FIX> 캠핑장 등록,수정 버그 수정

src/architecture/controllers/camps.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js, src/routes/camps.route.js
캠핑장 상세조회/등록 API 수정 및  캠핑장 키워드 체크박스 등록 API 삭제 했습니다.
=> <FIX> 캠핑장 상세조회/등록 API 수정 및  캠핑장 키워드 체크박스 등록 API 삭제 :art:

src/architecture/controllers/camps.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js, src/routes/camps.route.js
클라이언트 요청: 캠핑장 등록시 체크박스 null값으로 생성
=> <FIX> 캠핑장 상세조회/등록 API 수정 및 캠핑장 키워드 체크박스 등록 API 삭제 🎨

src/architecture/repositories/books.repository.js, src/architecture/repositories/camps.repository.js, src/architecture/services/books.service.js, src/architecture/services/camps.service.js
클라이언트 요청 :
-캠핑장 리스트 조회 시 typeLists추가
-유저/호스트 예약 리스트/상세 조회시 siteName, siteDesc,siteInfo,sitePrice,siteMainImage 추가
=> <FIX> 캠핑장 리스트 조회 시 typeLists추가 및 예약 조회시 sites 추가  #123 :art:

package-lock.json, package.json, src/architecture/controllers/auths.controller.js, src/architecture/repositories/auths.repository.js, src/architecture/services/auths.service.js, src/migrations/20221231053827-create-users.js, src/models/users.js, src/routes/auths.routes.js, src/routes/index.js
=> <FEAT> 카카오 로그인 구현

src/architecture/controllers/camps.controller.js, src/routes/camps.route.js
캠핑장 키워드 체크박스 API 메소드 PUT -> PATCH로 변경 및 코드 수정했습니다.
=> <FIX> 캠핑장 키워드 체크박스 API 메소드 수정 및 코드 수정 :art:

src/architecture/repositories/camps.repository.js
=> <FIX> 캠핑장 키워드 체크박스 API 수정 :art:

src/architecture/repositories/books.repository.js, src/architecture/services/books.service.js
클라이언트 요청
: 유저 예약 리스트 조회 시 campcheckIn/Out 추가
=> <FIX> user 예약 조회시 camps.checkIn/Out date 추가 :art: #115

src/architecture/services/books.service.js
클라이언트 요청 :
-특정 호스트 예약 조회시 camp checkin/out 추가
=> <FIX> host 예약 조회시 camps.checkIn/Out date 추가 :art: #115

src/routes/index.js
=> <FIX> 배포 날짜 변경  #115

src/architecture/services/books.service.js, src/migrations/20221231054909-create-books.js, src/models/books.js
=> <FIX> db타입수정, books 예외 처리추가 :twisted_rightwards_arrows:

src/architecture/controllers/reviews.controller.js, src/architecture/repositories/reviews.repository.js, src/architecture/services/reviews.service.js, src/migrations/20230111064415-create-reviews.js, src/models/reviews.js, src/routes/index.js, src/routes/reviews.route.js
=> <FEAT> 리뷰 작성, 조회, 수정, 삭제 API 기능 구현 완료  :sparkles:

.github/workflows/main.yml
=> <FIX> cicd env값 추가

src/app.js, src/architecture/controllers/books.controller.js, src/architecture/repositories/books.repository.js, src/architecture/services/books.service.js, src/architecture/services/camps.service.js, src/migrations/20221231054909-create-books.js, src/models/books.js, src/routes/books.route.js
유저 예약관련 기능 구현 완료했습니다
1. 유저 예약 기능 구현
2. 호스트 예약 확정 기능 구현
3. 유저 예약 목록 조회 기능 구현(checkoutdate가 지난 예약 및 취소된 예약 제외)
4. 유저 예약 취소 기능 구현
(호스트가 예약을 확정하지 않았을 때 가능/ 호스트가 예약을 확정했을 때에는 호스트 전화번호와 예약 취소 메세지를보냄)
5. 유저 예약 취소 리스트 조회 기능 구현
6. 유저 이용완료 목록 조회 기능 구현
(호스트가 예약을 확정하고 예약시 checkoutdate가 지난 예약 리스트만 조회가능)
=> <FEAT> 유저 예약 취소/ 호스트 예약 확정 및 확정 취소 구현 완료 ✨ #143

src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js
캠핑장 페이지 조회 시 해당 캠핑장의 리뷰 총 개수를 추가했습니다.
=> <FIX> 캠핑장 페이지 조회 API 수정 :memo:

src/architecture/repositories/camps.repository.js, src/architecture/repositories/likes.repository.js, src/architecture/services/camps.service.js, src/architecture/services/likes.service.js, src/middlewares/likeConfirmUserHost.middleware.js, src/models/likes.js, src/models/types.js, src/routes/camps.route.js
클라이언트 요청 
- 캠핑장 사이트 목록 조회 시 리뷰 개수 요청
- 라이크 조회시 캠프메인이미지, 주소, 타입 요청
- 호스트 캠핑장 상세 조회시 오류 수정
=> <FIX> 리뷰 관련 수정, like관련 수정, 캠핑장 상세조회 버그 수정 :art: :bug:

src/architecture/services/auths.service.js
=> <FIX> update .env file

src/architecture/controllers/camps.controller.js, src/architecture/repositories/camps.repository.js, src/architecture/services/auths.service.js, src/architecture/services/camps.service.js, src/routes/camps.route.js
[<FIX> 캠핑장 페이지 조회 API 수정 📝](https://github.com/gpwn/CampFire_BE/commit/3a56ab8c265538818212a9c0050c751ea9d2727a)
=> <FIX> 캠핑장 페이지 조회 API 수정 📝

src/architecture/repositories/camps.repository.js, src/architecture/services/camps.service.js
캠핑장 상세 조회 시 호스트 전화번호도 받게끔 수정했습니다.
=> <FIX> 캠핑장 상세 조회 API 수정

src/architecture/services/likes.service.js
=> <FIX> 유저 찜하기 목록 조회 수정 :art:

src/architecture/controllers/search.controller.js, src/architecture/repositories/search.repository.js, src/architecture/services/search.service.js
클라이언트 요청 수정
- 바디 값이 아닌 쿼리값 으로 수정
- subImages, checkIn/Out 데이터 불필요
=> <FIX> 통합 검색 기능 구형 수정

src/architecture/controllers/search.controller.js, src/architecture/repositories/search.repository.js, src/architecture/services/search.service.js
=> <FIX> 캠핑장 조회시 페이지네이션 기능 제거 :fire: #161

src/architecture/repositories/hosts.repository.js, src/architecture/services/hosts.service.js
특정 호스트 정보 조회 시 campList에 해당 호스트가 보유한 campId와 campName을 리스트로 보내도록 수정했습니다.
=> <FIX> 특정 호스트 정보 조회 API 수정 :memo:

src/architecture/repositories/books.repository.js, src/architecture/services/books.service.js
유저 예약 조회 관련 수정
유저 api를 호출할 시에 취소상태값과 이용완료 값을 변경하도록 수정하였습니다
=> <FIX> 유저 예약조회,이용완료조회,취소조회 기능 구현 수정 :art: #143

.github/workflows/main.yml
=> <FIX> docker 자동 재시작 :art:

src/architecture/controllers/search.controller.js, src/architecture/repositories/search.repository.js, src/architecture/services/search.service.js, src/routes/search.route.js
=> <FIX> 검색기능 해시 검색 추가 구현 🎨   #161

.github/workflows/main.yml, src/architecture/controllers/users.controller.js, src/architecture/services/auths.service.js, src/routes/index.js
=> <FIX> 검색 기능 관련 업데이트 🎨 #161

src/architecture/controllers/search.controller.js, src/architecture/repositories/search.repository.js
아무것도 검색하지 않을 때 전체 캠핑장 리스트가 나오도록 수정하였습니다.
=> <FIX> 검색기능 버그 수정 :bug: #161

src/architecture/controllers/search.controller.js, src/architecture/repositories/search.repository.js, src/architecture/services/search.service.js
=> <FIX> 검색기능 버그 수정 🐛 #161
